// Generated by CoffeeScript 1.7.1
(function() {
  window.WebserviceJSONConvert = (function() {
    function WebserviceJSONConvert() {}

    WebserviceJSONConvert.to_ui = function(doc) {
      var ui_hints;
      ui_hints = {
        display_name: null,
        primary_link: null,
        secondary_link: null
      };
      switch (doc.type) {
        case "Project":
          if (doc.attributes.name != null) {
            ui_hints.display_name = doc.attributes.name;
          }
          if (doc.links.experiments != null) {
            ui_hints.primary_link = doc.links.experiments;
          }
          ui_hints.secondary_link = null;
          break;
        case "Experiment":
          if (doc.attributes.purpose != null) {
            ui_hints.display_name = doc.attributes.purpose;
          }
          if (doc.links.epoch_groups != null) {
            ui_hints.primary_link = doc.links.epoch_groups;
          }
          if (doc.links.epoch != null) {
            ui_hints.secondary_link = doc.links.epoch;
          }
          break;
        case "EpochGroup":
          if (doc.attributes.label != null) {
            ui_hints.display_name = doc.attributes.label;
          }
          if (doc.links.children != null) {
            ui_hints.primary_link = doc.links.children;
          }
          if (doc.links.epochs != null) {
            ui_hints.secondary_link = doc.links.epochs;
          }
          break;
        case "Source":
          ui_hints.display_name = "" + (doc.attributes.label != null ? doc.attributes.label : void 0) + "(" + (doc.attributes.identifier != null ? doc.attributes.identifier : void 0) + ")";
          if (doc.links.children != null) {
            ui_hints.primary_link = doc.links.children;
          }
          if (doc.links.experiments != null) {
            ui_hints.secondary_link = doc.links.experiments;
          }
          break;
        case "Epoch":
          ui_hints.display_name = "" + (doc.attributes.label != null ? doc.attributes.label : void 0) + "(" + (doc.attributes.identifier != null ? doc.attributes.identifier : void 0) + ")";
          if (doc.links.measurements != null) {
            ui_hints.primary_link = doc.links.measurements;
          }
          ui_hints.secondary_link = typeof null !== "undefined" && null !== null;
          break;
        case "Measurement":
          ui_hints.display_name = "" + (doc.attributes.name != null ? doc.attributes.name : void 0);
          ui_hints.primary_link = null;
          ui_hints.secondary_link = null;
          break;
        case "AnalysisRecord":
          if (doc.attributes.name != null) {
            ui_hints.display_name = doc.attributes;
          }
          if (doc.links.outputs != null) {
            ui_hints.primary_link = doc.links.outputs;
          }
          if (doc.links.inputs != null) {
            ui_hints.secondary_link = doc.links.inputs;
          }
          break;
        case "Protocol":
          ui_hints.display_name = "" + (doc.attributes.name != null ? doc.attributes.name : void 0) + "(" + (doc.attributes.version != null ? doc.attributes.version : void 0) + ")";
          if (doc.links.children != null) {
            ui_hints.primary_link = doc.links.children;
          }
          if (doc.links.procedures != null) {
            ui_hints.secondary_link = doc.links.procedures;
          }
      }
      doc.ui_hints = ui_hints;
      return doc;
    };

    WebserviceJSONConvert.to_server = function(doc) {
      if (doc.hasOwnProperty("ui_hints")) {
        delete doc.ui_hints;
      }
      return doc;
    };

    return WebserviceJSONConvert;

  })();

}).call(this);
