// Generated by CoffeeScript 1.7.1
(function() {
  var Analysis;

  Analysis = OvationBaseModel.extend({
    initialize: function() {
      return this.urlRoot = "" + this.urlRoot + "/analysis/" + this.id;
    }
  });

}).call(this);
