// Generated by CoffeeScript 1.7.1
(function() {
  var Measurement;

  Measurement = OvationBaseModel.extend({
    initialize: function() {
      return this.urlRoot = "" + this.urlRoot + "/measurement/" + this.id;
    }
  });

}).call(this);
