// Generated by CoffeeScript 1.7.1
(function() {
  var Project;

  Project = OvationBaseModel.extend({
    initialize: function() {
      return this.urlRoot = "" + this.urlRoot + "/project/" + this.id;
    }
  });

}).call(this);
